// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockService is a mock of Service interface
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// Temperature mocks base method
func (m *MockService) Temperature(lat, lng float64) float64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Temperature", lat, lng)
	ret0, _ := ret[0].(float64)
	return ret0
}

// Temperature indicates an expected call of Temperature
func (mr *MockServiceMockRecorder) Temperature(lat, lng interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Temperature", reflect.TypeOf((*MockService)(nil).Temperature), lat, lng)
}
