version: '3'

services:
  zookeeper:
    image: bitnami/zookeeper:3.6.2
    volumes:
      - 'zookeeper_data:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: bitnami/kafka:2.6.0
    ports:
      - '9092:9092'
    volumes:
      - 'kafka_data:/bitnami'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  nats:
    image: bitnami/nats:2.1.8
    ports:
      - '4222:4222'
      - '8222:8222'

volumes:
  zookeeper_data:
  kafka_data:
