version: '3'

services:
  zookeeper:
    image: bitnami/zookeeper:3.6.2
    ports:
      - 2181
      - 2888
      - 3888
      - 8080
    volumes:
      - zookeeper_data:/bitnami
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:2.6.0
    ports:
      - 9092:9092
    volumes:
      - kafka_data:/bitnami
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  nats:
    image: bitnami/nats:2.1.8
    ports:
      - 4222:4222
      - 6222
      - 8222

  prometheus:
    image: prom/prometheus:v2.21.0
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
    depends_on:
      - nats-prometheus-exporter

  nats-prometheus-exporter:
    image: synadia/prometheus-nats-exporter:0.6.2
    ports:
      - 7777
    command:
      - -varz
      - -connz
      - -subz
      - http://nats:8222
    depends_on:
      - nats

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    depends_on:
      - prometheus

volumes:
  zookeeper_data:
  kafka_data:
  prometheus_data:
  grafana_data:
