scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:7777', 'zenly:7777', 'nats-prometheus-exporter:7777', 'kafka-prometheus-exporter:9308']
