{
 "title": "Zenly",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "30s,1m,5m,10m,15m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "kind", "label": "Kind", "query": "rate,increase" },
   {
    "name": "enricher",
    "query": "label_values(enricher_time_ms_bucket, enricher)"
   }
  ]
 },
 "panels": [
  {
   "title": "\"$enricher\" timeouts",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "repeat": "enricher",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(enricher_time_ms_count{enricher=\"$enricher\", timeout=\"true\"}[$interval])) / sum(increase(enricher_time_ms_count{enricher=\"$enricher\"}[$interval]))"
    }
   ]
  },
  {
   "title": "\"$enricher\" timeouts",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(enricher_time_ms_count{enricher=\"$enricher\", timeout=\"true\"}[$interval])) / sum(increase(enricher_time_ms_count{enricher=\"$enricher\"}[$interval]))"
    }
   ]
  },
  {
   "title": "\"$enricher\" timeouts",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(enricher_time_ms_count{enricher=\"$enricher\", timeout=\"true\"}[$interval])) / sum(increase(enricher_time_ms_count{enricher=\"$enricher\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Enrich timeouts",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(enrich_finish_ms_count{reason=\"timeout\"}[$interval])) / sum(increase(enrich_finish_ms_count[$interval]))"
    }
   ]
  },
  {
   "title": "Enrich time heatmap",
   "type": "graph",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 7 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum($kind(enrich_finish_ms_bucket[$interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}