// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: enricher/transport.proto

package enricher

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Transport_Type int32

const (
	Transport_CAR   Transport_Type = 0
	Transport_TRAIN Transport_Type = 1
	Transport_PLANE Transport_Type = 2
)

// Enum value maps for Transport_Type.
var (
	Transport_Type_name = map[int32]string{
		0: "CAR",
		1: "TRAIN",
		2: "PLANE",
	}
	Transport_Type_value = map[string]int32{
		"CAR":   0,
		"TRAIN": 1,
		"PLANE": 2,
	}
)

func (x Transport_Type) Enum() *Transport_Type {
	p := new(Transport_Type)
	*p = x
	return p
}

func (x Transport_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Transport_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_enricher_transport_proto_enumTypes[0].Descriptor()
}

func (Transport_Type) Type() protoreflect.EnumType {
	return &file_enricher_transport_proto_enumTypes[0]
}

func (x Transport_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Transport_Type.Descriptor instead.
func (Transport_Type) EnumDescriptor() ([]byte, []int) {
	return file_enricher_transport_proto_rawDescGZIP(), []int{0, 0}
}

type Transport struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type Transport_Type `protobuf:"varint,1,opt,name=type,proto3,enum=enricher.Transport_Type" json:"type,omitempty"`
}

func (x *Transport) Reset() {
	*x = Transport{}
	if protoimpl.UnsafeEnabled {
		mi := &file_enricher_transport_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Transport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transport) ProtoMessage() {}

func (x *Transport) ProtoReflect() protoreflect.Message {
	mi := &file_enricher_transport_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transport.ProtoReflect.Descriptor instead.
func (*Transport) Descriptor() ([]byte, []int) {
	return file_enricher_transport_proto_rawDescGZIP(), []int{0}
}

func (x *Transport) GetType() Transport_Type {
	if x != nil {
		return x.Type
	}
	return Transport_CAR
}

var File_enricher_transport_proto protoreflect.FileDescriptor

var file_enricher_transport_proto_rawDesc = []byte{
	0x0a, 0x18, 0x65, 0x6e, 0x72, 0x69, 0x63, 0x68, 0x65, 0x72, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73,
	0x70, 0x6f, 0x72, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x65, 0x6e, 0x72, 0x69,
	0x63, 0x68, 0x65, 0x72, 0x22, 0x60, 0x0a, 0x09, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72,
	0x74, 0x12, 0x2c, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x18, 0x2e, 0x65, 0x6e, 0x72, 0x69, 0x63, 0x68, 0x65, 0x72, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x70, 0x6f, 0x72, 0x74, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22,
	0x25, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x07, 0x0a, 0x03, 0x43, 0x41, 0x52, 0x10, 0x00,
	0x12, 0x09, 0x0a, 0x05, 0x54, 0x52, 0x41, 0x49, 0x4e, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x50,
	0x4c, 0x41, 0x4e, 0x45, 0x10, 0x02, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x68, 0x65, 0x6b, 0x68, 0x69, 0x72, 0x69, 0x6e, 0x2f, 0x7a,
	0x65, 0x6e, 0x6c, 0x79, 0x2d, 0x74, 0x61, 0x73, 0x6b, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x2f, 0x70, 0x62, 0x2f, 0x65, 0x6e, 0x72, 0x69, 0x63, 0x68, 0x65, 0x72, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_enricher_transport_proto_rawDescOnce sync.Once
	file_enricher_transport_proto_rawDescData = file_enricher_transport_proto_rawDesc
)

func file_enricher_transport_proto_rawDescGZIP() []byte {
	file_enricher_transport_proto_rawDescOnce.Do(func() {
		file_enricher_transport_proto_rawDescData = protoimpl.X.CompressGZIP(file_enricher_transport_proto_rawDescData)
	})
	return file_enricher_transport_proto_rawDescData
}

var file_enricher_transport_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_enricher_transport_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_enricher_transport_proto_goTypes = []interface{}{
	(Transport_Type)(0), // 0: enricher.Transport.Type
	(*Transport)(nil),   // 1: enricher.Transport
}
var file_enricher_transport_proto_depIdxs = []int32{
	0, // 0: enricher.Transport.type:type_name -> enricher.Transport.Type
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_enricher_transport_proto_init() }
func file_enricher_transport_proto_init() {
	if File_enricher_transport_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_enricher_transport_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Transport); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_enricher_transport_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_enricher_transport_proto_goTypes,
		DependencyIndexes: file_enricher_transport_proto_depIdxs,
		EnumInfos:         file_enricher_transport_proto_enumTypes,
		MessageInfos:      file_enricher_transport_proto_msgTypes,
	}.Build()
	File_enricher_transport_proto = out.File
	file_enricher_transport_proto_rawDesc = nil
	file_enricher_transport_proto_goTypes = nil
	file_enricher_transport_proto_depIdxs = nil
}
