// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: enricher/weather.proto

package enricher

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Weather struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Temperature float64 `protobuf:"fixed64,1,opt,name=temperature,proto3" json:"temperature,omitempty"`
}

func (x *Weather) Reset() {
	*x = Weather{}
	if protoimpl.UnsafeEnabled {
		mi := &file_enricher_weather_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Weather) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Weather) ProtoMessage() {}

func (x *Weather) ProtoReflect() protoreflect.Message {
	mi := &file_enricher_weather_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Weather.ProtoReflect.Descriptor instead.
func (*Weather) Descriptor() ([]byte, []int) {
	return file_enricher_weather_proto_rawDescGZIP(), []int{0}
}

func (x *Weather) GetTemperature() float64 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

var File_enricher_weather_proto protoreflect.FileDescriptor

var file_enricher_weather_proto_rawDesc = []byte{
	0x0a, 0x16, 0x65, 0x6e, 0x72, 0x69, 0x63, 0x68, 0x65, 0x72, 0x2f, 0x77, 0x65, 0x61, 0x74, 0x68,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x65, 0x6e, 0x72, 0x69, 0x63, 0x68,
	0x65, 0x72, 0x22, 0x2b, 0x0a, 0x07, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x12, 0x20, 0x0a,
	0x0b, 0x74, 0x65, 0x6d, 0x70, 0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x0b, 0x74, 0x65, 0x6d, 0x70, 0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65, 0x42,
	0x36, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x68,
	0x65, 0x6b, 0x68, 0x69, 0x72, 0x69, 0x6e, 0x2f, 0x7a, 0x65, 0x6e, 0x6c, 0x79, 0x2d, 0x74, 0x61,
	0x73, 0x6b, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x62, 0x2f, 0x65,
	0x6e, 0x72, 0x69, 0x63, 0x68, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_enricher_weather_proto_rawDescOnce sync.Once
	file_enricher_weather_proto_rawDescData = file_enricher_weather_proto_rawDesc
)

func file_enricher_weather_proto_rawDescGZIP() []byte {
	file_enricher_weather_proto_rawDescOnce.Do(func() {
		file_enricher_weather_proto_rawDescData = protoimpl.X.CompressGZIP(file_enricher_weather_proto_rawDescData)
	})
	return file_enricher_weather_proto_rawDescData
}

var file_enricher_weather_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_enricher_weather_proto_goTypes = []interface{}{
	(*Weather)(nil), // 0: enricher.Weather
}
var file_enricher_weather_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_enricher_weather_proto_init() }
func file_enricher_weather_proto_init() {
	if File_enricher_weather_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_enricher_weather_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Weather); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_enricher_weather_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_enricher_weather_proto_goTypes,
		DependencyIndexes: file_enricher_weather_proto_depIdxs,
		MessageInfos:      file_enricher_weather_proto_msgTypes,
	}.Build()
	File_enricher_weather_proto = out.File
	file_enricher_weather_proto_rawDesc = nil
	file_enricher_weather_proto_goTypes = nil
	file_enricher_weather_proto_depIdxs = nil
}
